version: "3.8"

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
  
  mysql_server:
    image: mysql:8.0
    environment: 
      - MYSQL_DATABASE=sociality_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=root
   
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql_server
    ports:
      - "3001:80"
    environment:
      - PMA_HOST=mysql_server
      - PMA_PORT=3306
    volumes:
      - /sessions
    container_name: moe-phpmyadmin-app
    